In [1]:
import processador as pc
import geradorListaInvertida as gli
import indexador
import buscador
import os
import pandas as pd
os.listdir()

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\sylvi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\sylvi\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['buscador.py',
 'geradorListaInvertida.py',
 'indexador.py',
 'main.py',
 'notebook.ipynb',
 'processador.py',
 'test.py',
 '__pycache__']

In [2]:
leitura, consultas, esperado = pc.read_config("PC.CFG")
xml_root = pc.gerar_raiz_xml(leitura)
pc.gerar_arquivo_consultas(consultas, xml_root)
pc.gerar_arquivo_esperado(esperado, xml_root)

In [3]:


consultas_df = pd.read_csv(consultas, sep=';')
esperado_df  = pd.read_csv(esperado,  sep=';')

consultas_df.head()

   QueryNumber                                          QueryText
0            1  WHAT ARE THE EFFECTS OF CALCIUM ON THE PHYSICA...
1            2  CAN ONE DISTINGUISH BETWEEN THE EFFECTS OF MUC...
2            3  HOW ARE SALIVARY GLYCOPROTEINS FROM CF PATIENT...
3            4  WHAT IS THE LIPID COMPOSITION OF CF RESPIRATOR...
4            5                              IS CF MUCUS ABNORMAL?

In [4]:
esperado_df.head()

   QueryNumber  DocNumber  DocVotes
0            1        139         4
1            1        151         4
2            1        166         1
3            1        311         1
4            1        370         2

In [2]:
ler_arquivos, escrever_arquivo = gli.read_config_file("GLI.CFG")
gli.gerar_arquivo_tokens(ler_arquivos, escrever_arquivo)
inverted_list = pd.read_csv(escrever_arquivo, sep=";", converters={"Appearance": pd.eval})
inverted_list.head()

         Token                                         Appearance
0     SIGNIFIC  [1, 6, 19, 24, 30, 47, 52, 53, 54, 62, 62, 65,...
1   PSEUDOMONA  [1, 1, 1, 7, 8, 18, 18, 61, 61, 62, 62, 62, 62...
2   AERUGINOSA  [1, 1, 1, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, ...
3       INFECT  [1, 1, 1, 6, 6, 6, 16, 18, 48, 48, 57, 58, 58,...
4  RESPIRATORI  [1, 1, 1, 6, 6, 7, 7, 8, 11, 11, 11, 15, 17, 2...

In [3]:
tokens, model = indexador.read_config_file("INDEX.CFG")
matrix = indexador.gerar_matriz_termos_documentos(tokens)
matrix

,1,6,19,24,30,47,52,53,54,62,...,909,330,537,580,799,558,908,117,1011,940
Token,,,,,,,,,,,,,,,,,,,,,
SIGNIFIC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PSEUDOMONA,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AERUGINOSA,3.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
INFECT,3.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
RESPIRATORI,3.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
THROMBOSI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
MONOSPECIF,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
CONSENT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
PATCHI,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
THEORIZ,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
type_tf = "tfn"
model = indexador.carregar_modelo(matrix, type_tf)

100%|██████████| 6278/6278 [19:51<00:00,  5.27it/s]